let code
export const svg = `<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN"
 "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd">
<!-- Generated by graphviz version 2.40.1 (20161225.0304)
 -->
<!-- Title: ATN Pages: 1 -->
<svg width="496pt" height="106pt"
 viewBox="0.00 0.00 496.22 106.00" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
<g id="graph0" class="graph" transform="scale(1 1) rotate(0) translate(4 102)">
<title>ATN</title>
<polygon fill="#ffffff" stroke="transparent" points="-4,4 -4,-102 492.2204,-102 492.2204,4 -4,4"/>
<!-- s149 -->
<g id="node1" class="node">
<title>s149</title>
<ellipse fill="none" stroke="#000000" cx="462.7204" cy="-51" rx="21.5" ry="21.5"/>
<ellipse fill="none" stroke="#000000" cx="462.7204" cy="-51" rx="25.5" ry="25.5"/>
<text text-anchor="middle" x="462.7204" y="-47.7" font-family="Times,serif" font-size="11.00" fill="#000000">149</text>
</g>
<!-- s1155 -->
<g id="node2" class="node">
<title>s1155</title>
<ellipse fill="none" stroke="#000000" cx="211.2741" cy="-78" rx="20" ry="20"/>
<text text-anchor="middle" x="211.2741" y="-74.7" font-family="Times,serif" font-size="11.00" fill="#000000">1155</text>
</g>
<!-- s1158 -->
<g id="node6" class="node">
<title>s1158</title>
<ellipse fill="none" stroke="#000000" cx="373.0598" cy="-51" rx="20" ry="20"/>
<text text-anchor="middle" x="373.0598" y="-54.3" font-family="Times,serif" font-size="11.00" fill="#000000">←</text>
<text text-anchor="middle" x="373.0598" y="-41.1" font-family="Times,serif" font-size="11.00" fill="#000000">1158</text>
</g>
<!-- s1155&#45;&gt;s1158 -->
<g id="edge4" class="edge">
<title>s1155&#45;&gt;s1158</title>
<path fill="none" stroke="#000000" d="M231.1122,-74.6893C260.0584,-69.8585 313.9408,-60.8662 346.3483,-55.4578"/>
<polygon fill="#000000" stroke="#000000" points="346.8116,-57.8645 353.3127,-54.2955 346.0049,-53.0313 346.8116,-57.8645"/>
<text text-anchor="middle" x="292.167" y="-74.3" font-family="Courier,monospace" font-size="11.00" fill="#000000">&lt;statement&gt;</text>
</g>
<!-- s148 -->
<g id="node3" class="node">
<title>s148</title>
<ellipse fill="none" stroke="#000000" cx="20" cy="-49" rx="20" ry="20"/>
<text text-anchor="middle" x="20" y="-45.7" font-family="Times,serif" font-size="11.00" fill="#000000">148</text>
</g>
<!-- s1157 -->
<g id="node5" class="node">
<title>s1157</title>
<polygon fill="none" stroke="#000000" points="84.1606,-25.2 84.1606,-72.8 147.1135,-72.8 147.1135,-25.2 84.1606,-25.2"/>
<text text-anchor="middle" x="106.262" y="-58.9" font-family="Times,serif" font-size="11.00" fill="#000000">→</text>
<text text-anchor="middle" x="106.262" y="-45.7" font-family="Times,serif" font-size="11.00" fill="#000000">1157</text>
<text text-anchor="middle" x="106.262" y="-32.5" font-family="Times,serif" font-size="11.00" fill="#000000">d=121</text>
<polyline fill="none" stroke="#000000" points="128.3635,-25.2 128.3635,-72.8 "/>
<text text-anchor="middle" x="137.7385" y="-57.9" font-family="Times,serif" font-size="11.00" fill="#000000"> </text>
<polyline fill="none" stroke="#000000" points="128.3635,-49.6 147.1135,-49.6 "/>
<text text-anchor="middle" x="137.7385" y="-34.2" font-family="Times,serif" font-size="11.00" fill="#000000"> </text>
</g>
<!-- s148&#45;&gt;s1157 -->
<g id="edge1" class="edge">
<title>s148&#45;&gt;s1157</title>
<path fill="none" stroke="#000000" d="M40.2822,-49C50.1209,-49 62.3188,-49 74.0139,-49"/>
<polygon fill="#000000" stroke="#000000" points="74.09,-52.5001 84.09,-49 74.09,-45.5001 74.09,-52.5001"/>
<text text-anchor="middle" x="62.0803" y="-53.2" font-family="Times,serif" font-style="italic" font-size="14.00" fill="#000000">ε</text>
</g>
<!-- s1156 -->
<g id="node4" class="node">
<title>s1156</title>
<ellipse fill="none" stroke="#000000" cx="211.2741" cy="-20" rx="20" ry="20"/>
<text text-anchor="middle" x="211.2741" y="-16.7" font-family="Times,serif" font-size="11.00" fill="#000000">1156</text>
</g>
<!-- s1156&#45;&gt;s1158 -->
<g id="edge5" class="edge">
<title>s1156&#45;&gt;s1158</title>
<path fill="none" stroke="#000000" d="M231.1471,-22.3815C255.7249,-25.5092 298.7621,-31.5834 335.0598,-39.8 338.9169,-40.6731 342.9585,-41.7191 346.9069,-42.8161"/>
<polygon fill="#000000" stroke="#000000" points="346.449,-45.2339 353.8538,-44.8198 347.807,-40.5258 346.449,-45.2339"/>
<text text-anchor="middle" x="292.167" y="-42.3" font-family="Courier,monospace" font-size="11.00" fill="#000000">&lt;declaration&gt;</text>
</g>
<!-- s1157&#45;&gt;s1155 -->
<g id="edge2" class="edge">
<title>s1157:p0&#45;&gt;s1155</title>
<path fill="none" stroke="#000000" d="M146.637,-61C158.8079,-61 171.8563,-63.8539 183.0201,-67.2231"/>
<polygon fill="#000000" stroke="#000000" points="182.0704,-70.5951 192.6633,-70.395 184.2576,-63.9456 182.0704,-70.5951"/>
<text text-anchor="middle" x="169.1938" y="-68.2" font-family="Times,serif" font-style="italic" font-size="14.00" fill="#000000">ε</text>
</g>
<!-- s1157&#45;&gt;s1156 -->
<g id="edge3" class="edge">
<title>s1157:p1&#45;&gt;s1156</title>
<path fill="none" stroke="#000000" d="M146.637,-37C158.8079,-37 171.8563,-34.1461 183.0201,-30.7769"/>
<polygon fill="#000000" stroke="#000000" points="184.2576,-34.0544 192.6633,-27.605 182.0704,-27.4049 184.2576,-34.0544"/>
<text text-anchor="middle" x="169.1938" y="-39.2" font-family="Times,serif" font-style="italic" font-size="14.00" fill="#000000">ε</text>
</g>
<!-- s1158&#45;&gt;s149 -->
<g id="edge6" class="edge">
<title>s1158&#45;&gt;s149</title>
<path fill="none" stroke="#000000" d="M393.4052,-51C403.2946,-51 415.4772,-51 426.8562,-51"/>
<polygon fill="#000000" stroke="#000000" points="426.9917,-54.5001 436.9916,-51 426.9916,-47.5001 426.9917,-54.5001"/>
<text text-anchor="middle" x="415.1401" y="-55.2" font-family="Times,serif" font-style="italic" font-size="14.00" fill="#000000">ε</text>
</g>
</g>
</svg>
`
